# Generated by Django 5.2.13 on 2026-05-20 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_address_customuser_citizen_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='citizen_id',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Citizen ID must contain exactly 12 digits.', regex='^\\d{12}$')]),
        ),
    ]
