# Generated by Django 5.2.13 on 2026-05-22 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('savings', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingplan',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saving_accounts', to='users.customer'),
        ),
        migrations.AddField(
            model_name='savingplan',
            name='saving_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='savings.savingtype'),
        ),
        migrations.AddField(
            model_name='savingtyperatehistory',
            name='saving_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='savings.savingtype'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='saving_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='savings.savingplan'),
        ),
    ]
