# Generated by Django 5.2.13 on 2026-05-20 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_savingaccount_interest_last_applied_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingaccount',
            name='address',
        ),
        migrations.RemoveField(
            model_name='savingaccount',
            name='citizen_id',
        ),
        migrations.RemoveField(
            model_name='savingaccount',
            name='name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='name',
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='savings.savingaccount'),
        ),
    ]
