# Generated by Django 5.2.13 on 2026-05-25 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_parameter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingplan',
            old_name='user',
            new_name='customer',
        ),
    ]
