# Generated by Django 5.2.13 on 2026-05-21 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_alter_savingaccount_user'),
        ('users', '0004_remove_customuser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingaccount',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saving_accounts', to='users.customer'),
        ),
    ]
