# Generated by Django 5.2.13 on 2026-05-26 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_rename_user_savingplan_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingplan',
            old_name='account_number',
            new_name='plan_id',
        ),
    ]
